-- smdb.blood_requests definition

CREATE TABLE `blood_requests` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `hn` varchar(20) NOT NULL DEFAULT '',
  `an` varchar(20) NOT NULL DEFAULT '',
  `patient_name` varchar(200) NOT NULL DEFAULT '',
  `diag` varchar(255) NOT NULL DEFAULT '',
  `doctor` varchar(200) NOT NULL DEFAULT '',
  `ptright` varchar(100) NOT NULL DEFAULT '',
  `hct` varchar(20) NOT NULL DEFAULT '',
  `got_blood` tinyint(1) NOT NULL DEFAULT '0',
  `get_blood_date` date DEFAULT NULL,
  `hospital` varchar(200) NOT NULL DEFAULT '',
  `blood_group` varchar(50) NOT NULL DEFAULT '',
  `blood_group_rh` varchar(50) NOT NULL DEFAULT '',
  `prc` tinyint(1) NOT NULL DEFAULT '0',
  `prc_unit` varchar(20) NOT NULL DEFAULT '',
  `lrpc` tinyint(1) NOT NULL DEFAULT '0',
  `lrpc_unit` varchar(20) NOT NULL DEFAULT '',
  `ffp` tinyint(1) NOT NULL DEFAULT '0',
  `ffp_unit` varchar(20) NOT NULL DEFAULT '',
  `plt_conc` tinyint(1) NOT NULL DEFAULT '0',
  `plt_conc_unit` varchar(20) NOT NULL DEFAULT '',
  `sdp` tinyint(1) NOT NULL DEFAULT '0',
  `sdp_unit` varchar(20) NOT NULL DEFAULT '',
  `other_blood` tinyint(1) NOT NULL DEFAULT '0',
  `other_other` varchar(200) NOT NULL DEFAULT '',
  `reason` varchar(100) NOT NULL DEFAULT '',
  `other_reason` varchar(255) NOT NULL DEFAULT '',
  `blood_order_date` date DEFAULT NULL,
  `blood_used_date` date DEFAULT NULL,
  `doctor_order` varchar(200) NOT NULL DEFAULT '',
  `nurse` varchar(200) NOT NULL DEFAULT '',
  `date_drawn` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `active` varchar(5) NOT NULL DEFAULT '',
  `date_active` varchar(10) NOT NULL DEFAULT '',
  `replacement_units` varchar(20) NOT NULL DEFAULT '',
  `ward` varchar(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `blood_requests_hn_IDX` (`hn`) USING BTREE,
  KEY `blood_requests_an_IDX` (`an`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;